server:
  port: 80
  servlet:
    context-path: /app
spring:
  banner:
    image:
      location: classpath:banner.txt
  datasource:
    url: jdbc:postgresql://localhost:5432/bz
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    jwt:
      secret: bashir
      expirationDateInMs: 18000000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    username: bashir.z2004@gmail.com
    password: dsmvjlgryrtmieul
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
bzamani:
  organization-id-for-guest-users: 2
